package master.dht.nio.protocol;

public enum ReqType {
    SERVER_REPORT,

    JOIN, TABLE, HEART_BEAT, TABLE_UPDATE,

    CREATE_FILE, OPEN_FILE, DELETE_FILE, COMMIT_FILE, BLOCK_LOCK, NEW_BLOCK, META_UPDATE,

    READ_FILE, WRITE_FILE, WRITE_INIT, WRITE_FINISH,

    DIR_ADD_FILE, DIR_DELETE_FILE, DIR_LIST_STATUS,
    
    LOAD_BAL

}
